name: ocr
on:
  issues:
    types: [opened]

jobs:
  ocr:
    name: OCR
    if: ${{ startsWith(github.event.issue.title, '[自动化文稿录入]') }}
    runs-on: ubuntu-latest
    container:
      image: breezedeus/cnocr:v2.2
      options: --user root
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: prefix${{ env.GITHUB_ACTION }}${{ env.GITHUB_RUN_NUMBER }}${{ github.sha }}${{ steps.time.outputs.time }}
      - run: add-apt-repository -y ppa:git-core/ppa
      - run: apt update
      - run: apt install git -y
      - run: pip install pymupdf
      - run: useradd -u 1001 ci
      - run: git config --global --add safe.directory "*"
      - name: clone
        run: |
          git config --system credential.helper store
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          echo "https://banned-historical-archives:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials
          git config --global submodule.token ${{ secrets.GH_PAT }}
          git clone --depth 1 https://github.com/banned-historical-archives/banned-historical-archives.github.io.git
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: node init
        working-directory: ./banned-historical-archives.github.io
        run: |
          npm i
      - id: get_archive_id
        working-directory: ./banned-historical-archives.github.io
        run: echo ::set-output name=archive_id::$(npx ts-node --project ./tsconfig.build.json backend/ocr-gitworkflow-get-archive-id.ts)
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - name: init subm
        working-directory: ./banned-historical-archives.github.io
        run: |
          rm -rf public/archives${{ steps.get_archive_id.outputs.archive_id }}
          git clone https://github.com/banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }} public/archives${{ steps.get_archive_id.outputs.archive_id }}
          chown -R ci:ci ./
      - id: action_with_json_output
        working-directory: ./banned-historical-archives.github.io
        run: echo ::set-output name=data::$(npx ts-node --project ./tsconfig.build.json backend/ocr-gitworkflow.ts)
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
      - name: prettier
        working-directory: ./banned-historical-archives.github.io
        run: npx npm run prettier
      - name: Create Pull Request
        working-directory: ./banned-historical-archives.github.io
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
        run: |
          git checkout -b feat/${{ steps.generate-uuid.outputs.uuid }}
          git add ./
          echo $TITLE
          echo "__ $TITLE"
          git commit -m $TITLE
          git push origin feat/${{ steps.generate-uuid.outputs.uuid }}
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -d '{
            "title": "$TITLE",
            "body": "fix #${{ github.event.issue.number }}",
            "head": "feat/${{ steps.generate-uuid.outputs.uuid }}",
            "base": "master"
          }' \
          https://api.github.com/repos/banned-historical-archives/banned-historical-archives.github.io/pulls
      - name: Create Pull Request For Submodule
        working-directory: ./banned-historical-archives.github.io
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
        run: |
          cd public/archives${{ steps.get_archive_id.outputs.archive_id }}
          git checkout -b feat/${{ steps.generate-uuid.outputs.uuid }}
          git add .
          git commit -m "feat: $TITLE"
          git push origin feat/${{ steps.generate-uuid.outputs.uuid }}
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          https://api.github.com/repos/banned-historical-archives/banned-historical-archives${{ steps.get_archive_id.outputs.archive_id }}/pulls \
          -d '{"title":"$TITLE","body":"https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/${{github.event.issue.number}}","head":"feat/${{ steps.generate-uuid.outputs.uuid }}","base":"main"}'
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.issue.number}}
          body: ${{ steps.action_with_json_output.outputs.data }}
